### ISSUE TITLE
support random access to all points in the route

### ISSUE THREAD

**Issue by jpahullo** [juacas/moodle-mod_treasurehunt#56] opened 2023-03-22 20:50 UTC
It seems interesting that, in certain scenarios, the user could pass through all checkpoints in a random order, instead of a sequential order as it works now. 

I think it would be a setting for the activity instance, set by the teacher at will. By default, it would keep sequential in-order to keep backwards compatibility.

**Comment by juacas** [comment] 2023-03-23 13:23
This is a duplicate of #54

**Closed by juacas** 2023-03-23 13:23 UTC
